<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Jugador;

class JugadorSeeder extends Seeder
{

    public function run()
    {
        $jugadores = [
            'Rakitić',
            'Dani Carvajal',
            'Jefferson Portales4',
            'Oblak',
            'Victor Balta3',
            'Sergio Ramos',
            'Ronal Huaccha18',
            'Joazhiño Arroé10',
            'Víctor Peña23',
            'Rodri',
            'Irven Avila',
            'Alejandro Gálvez',
            'Mathias Llontop30',
            'Moisés Velásquez33',
            'Thiago Silva',
            'Firmino',
            'Cavani',
            'Hugo Lloris',
            'Walter Tandazo19',
            'Franco Zanelatto',
            'Pedro Ibañez29',
            'Gaspar Gentile11',
            'Hugo Angeles2',
            'Luis Garro3',
            'José Rosell4',
            'Varane',
            'Kroos',
            'Eriksen',
            'Jordan Guivin8',
            'Carlos Torres12',
            'Lewandowski',
            'Marquinhos',
            'Isco',
            'Mats Hummels',
            'Pjanić',
            'Pogba',
            'Courtois',
            'Milan Škriniar',
            'Mbappé',
            'Daniel Morales13',
            'José Luján6',
            'Yamir Oliva20',
            'De Gea',
            'Toby Alderweireld',
            'Cristiano Ronaldo',
            'Leonardo Bonucci',
            'Jimmy Valoyes4',
            'Jeremi Escate7',
            'Francisco Duclós14',
            'Fabinho',
            'Marco Reus',
            'Zlatan Ibrahimović',
            'Kane',
            'Niklas Süle',
            'Hernan Dario',
            'Griezmann',
            'Coutinho',
            'Allan',
            'Alec Deneumostier15',
            'David Silva',
            'Werner Schuler',
            'Sebastian Cavero23',
            'Hernán Hinostroza26',
            'Mauro Icardi',
            'Dries Mertens',
            'Sergej Milinković-Savić',
            'Alfonso Barco44',
            'Anthony Fuentes14',
            'Didier La Torre',
            'Piero Vivanco26',
            'Rinaldo Cruzado18',
            'Dylan Caro29',
            'Rubert Quijada3',
            'Daniel Parejo',
            'Koke',
            'Sebastien Pineau22',
            'Marcos Lliuya19',
            'Godín',
            'Marcio Valverde32',
            'Luis Campos',
            'Carlos Neumann9',
            'Emilio Saba25',
            'Alexandre Lacazette',
            'Frenkie de Jong',
            'Gibson Fuentes8',
            'Kevin Ferreyra15',
            'Bryan Ríos',
            'Miguel Cornejo28',
            'Yimy Gamero',
            'José Bolivar14',
            'Antonio Huamán',
            'Giancarlo Carmona25',
            'Fabricio Cabrera16',
            'Nicolás Figueroa17',
            'Fernandinho',
            'Thomas Müller',
            'Carlos Neyra24',
            'Kluiverth Aguilar30',
            'Patricio Rubio9',
            'Jesús Pretel4',
            'Alejandro Gómez',
            'Edson Aubert20',
            'Casemiro',
            'Héctor Salazar2',
            'Gerard Piqué',
            'Alexi Gómez12',
            'Hector Bazan29',
            'Matías Lazo',
            'Leonardo Mifflin27',
            'Modrić',
            'Mohamed Salah',
            'Carlos Beltrán13',
            'Andrew Robertson',
            'Jairo Concha10',
            'Van Dijk',
            'Luis Aguiar8',
            'Samir Handanovič',
            'Joseph Vega',
            'Joel Amoroso7',
            'Francesco Cavagna25',
            'Wojciech Szczęsny',
            'Messi',
            'Joshua Kimmich',
            'Marcelo',
            'Carlos Caraza24',
            'Dybala',
            'Sergio Agüero',
            'Jordi Alba',
            'Josepmir Ballón21',
            'Paolo Reyna23',
            'Othoniel Arce9',
            'José María Giménez',
            'Mané',
            'Alex Sandro',
            'Sebastián Gonzáles',
            'Bruno Fernandes',
            'Michael Rasmussen18',
            'Heung Min Son',
            'Hazard',
            'Rodrigo Menancho',
            'Mohamed Karamoko9',
            'Sergio Busquets',
            'Marcelo Olivera34',
            'Carlos Jiménez',
            'Jonathan Bilbao2',
            'Blaise Matuidi',
            'Bernardo Silva',
            'Kevin de Bruyne',
            'Aubameyang',
            'Ederson',
            'Santiago Rebagliati18',
            'Alberto Rodríguez5',
            'Leroy Sané',
            'Di María',
            'Alisson',
            'Paolo Fuentes6',
            'NGolo Kanté',
            'Franco Medina19',
            'Luis Suárez',
            'Jefferson Caceres33',
            'Gianluigi Donnarumma',
            'Keylor Navas',
            'Axel Witsel',
            'Ter Stegen',
            'Cristian Zúñiga17',
            'Carlos Montoya26',
            'Kenji Cabrera',
            'Elffer Zambrano',
            'Milton Benitez10',
            'Jorge Bazán15',
            'Gonzalo Sánchez16',
            'Kostas Manolas',
            'Marco Verratti',
            'Neymar Jr.',
            'Diego Rodriguez',
            'Aymeric Laporte',
            'Lorenzo Insigne',
            'Luiz Da',
            'De Ligt',
            'Óscar Pinto22',
            'Romelu Lukaku',
            'Charles Monsalvo20',
            'Ciro Immobile',
            'Oslimg Mora25',
            'Jan Vertonghen',
            'Saúl',
            'Eduardo Rabanal39',
            'Samuel Umtiti',
            'Alfredo Rojas6',
            'James Rodríguez',
            'Thiago',
            'Benzema',
            'Joe Martínez26',
            'Raheem Sterling',
            'Omar Tejeda13',
            'Jeremy Salas5',
            'Kalidou Koulibaly',
            'David Alaba',
            'Leonardo Villar17',
            'Chiellini',
            'Neuer',
            'Johnny Vidales14',
            'Saúl Salas23',
            'Hakim Ziyech',
            'Pablo Míguez8',
            'Joel Sánchez10',
            'Hideyoshi Arakaki17',
            'Herve Kambou5',
            'Carlos Ascues6',
        ];

        foreach ($jugadores as $value) {
            Jugador::factory()->create(['nombre' => $value]);
        }
    }
}
